# Generated by Django 5.2 on 2025-04-13 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 13, 10, 32, 48, 130288)),
        ),
    ]
