# Generated by Django 5.2 on 2025-04-13 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasktemplate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplate',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 13, 10, 33, 44, 409227, tzinfo=datetime.timezone.utc)),
        ),
    ]
