# Generated by Django 5.2 on 2025-04-13 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasktemplate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplate',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
