# Generated by Django 5.2 on 2025-04-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_taskinstance_assignee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskinstance',
            name='date',
        ),
    ]
