# Generated by Django 5.2 on 2025-04-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_taskinstance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskinstance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired'), ('pending_review', 'Pending Review')], default='pending', max_length=32),
        ),
    ]
